pub mod agc;
pub mod dc_removal;
pub mod filter;
pub mod fir_bandpass;
pub mod fir_core;
pub mod fir_highpass;
pub mod moving_average;
pub mod peak_detector;
pub mod zero_crossing_detector;

pub use agc::AutomaticGainControl;
pub use dc_removal::DcRemover;
pub use filter::Filter;
pub use fir_bandpass::FirBandpass;
pub use fir_core::FirFilterCore;
pub use fir_highpass::FirHighpass;
pub use moving_average::MovingAverage;
pub use peak_detector::PeakDetector;
pub use zero_crossing_detector::ZeroCrossingDetector;
