#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Dict, Tuple

from perf_schema import (
    assert_metrics_are_current,
    read_metrics,
    write_metrics,
    coverage_failures,
    fine_coverage_failures,
    MetricSpec,
    evaluate_row_against_limits,
    unsupported_metrics,
    render_markdown_table,
    summarize_rows,
)

# Timing spread is machine load, which no number of draws averages away, so
# those columns are not asked whether they support a verdict.
SUPPORT_EXEMPT = ("mean_us_per_sample", "p95_us_per_sample")
# A bearing error cannot exceed 180 degrees. A limit at or above that cannot
# be crossed, so its margin is not a real one and must not demand precision.
PHYSICAL_MAX = {"mean_abs_bearing_error_deg": 180.0, "p95_abs_bearing_error_deg": 180.0,
    "max_abs_bearing_error_deg": 180.0}

EPSILON = 1e-6

METRICS = [
    MetricSpec("success_rate", "min", "success_rate", "{:.6f}"),
    MetricSpec("mean_us_per_sample", "max", "mean_us_per_sample", "{:.9f}"),
    MetricSpec("p95_us_per_sample", "max", "p95_us_per_sample", "{:.9f}"),
    MetricSpec(
        "mean_abs_bearing_error_deg",
        "max",
        "mean_abs_bearing_error_deg",
        "{:.6f}",
    ),
    MetricSpec(
        "p95_abs_bearing_error_deg",
        "max",
        "p95_abs_bearing_error_deg",
        "{:.6f}",
    ),
    MetricSpec(
        "max_abs_bearing_error_deg",
        "max",
        "max_abs_bearing_error_deg",
        "{:.6f}",
    ),
]

# The per-sample budgets carry the 1023-tap doppler bandpass, an eightfold
# convolution over the 127 taps the old budgets were set for, bought
# deliberately: realizing the filter took low_snr_dc's mean bearing error
# from 6.0 to 1.0 degrees. Measured worst after the change is 0.92 us per
# sample -- 4.4 percent of the 20.8 us real-time budget at 48 kHz -- but the
# same binary has read anywhere from 0.9 to 2.5 across sessions with host
# load, so the limits carry that variance rather than one quiet reading:
# they exist to catch an algorithmic blowup, not to referee the scheduler.
# Generated by scripts/rederive_limits.py from a fresh gate run; regenerate
# with it after any change that moves the numbers, and let the diff document
# the move. One mechanical policy for every accuracy limit -- worst measured
# row plus three inflated standard errors, times 1.5 for error columns, plus
# 0.01 for false-positive rates, minus 0.02 for detection floors -- so a
# limit is always close enough to measurement to fail. Timing columns are
# added below on their own policy: they carry measured cross-session host
# variance (0.9 to 2.5 us/sample on identical code) and exist to catch
# algorithmic blowups, not to referee the scheduler.
BASELINE_LIMITS: Dict[Tuple[str, str], Dict[str, float]] = {
    ("correlation", "clean"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 2.03,
        "p95_abs_bearing_error_deg": 3.18,
        "max_abs_bearing_error_deg": 3.24,
    },
    ("correlation", "dc_offset"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 2.05,
        "p95_abs_bearing_error_deg": 3.34,
        "max_abs_bearing_error_deg": 3.8,
    },
    ("correlation", "harmonic_contaminated"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 2.06,
        "p95_abs_bearing_error_deg": 3.4,
        "max_abs_bearing_error_deg": 3.97,
    },
    ("correlation", "low_snr_dc"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 4.81,
        "p95_abs_bearing_error_deg": 12.0,
        "max_abs_bearing_error_deg": 25.4,
    },
    ("correlation", "multipath_like"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 2.06,
        "p95_abs_bearing_error_deg": 3.43,
        "max_abs_bearing_error_deg": 4.05,
    },
    ("correlation", "noisy"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 2.1,
        "p95_abs_bearing_error_deg": 3.75,
        "max_abs_bearing_error_deg": 4.64,
    },
    ("zero_crossing", "clean"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 0.225,
        "p95_abs_bearing_error_deg": 0.632,
        "max_abs_bearing_error_deg": 0.695,
    },
    ("zero_crossing", "dc_offset"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 0.204,
        "p95_abs_bearing_error_deg": 0.525,
        "max_abs_bearing_error_deg": 1.17,
    },
    ("zero_crossing", "harmonic_contaminated"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 0.26,
        "p95_abs_bearing_error_deg": 0.629,
        "max_abs_bearing_error_deg": 1.51,
    },
    ("zero_crossing", "low_snr_dc"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 4.49,
        "p95_abs_bearing_error_deg": 11.1,
        "max_abs_bearing_error_deg": 24.6,
    },
    ("zero_crossing", "multipath_like"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 0.336,
        "p95_abs_bearing_error_deg": 0.782,
        "max_abs_bearing_error_deg": 1.76,
    },
    ("zero_crossing", "noisy"): {
        "success_rate": 0.98,
        "mean_abs_bearing_error_deg": 0.45,
        "p95_abs_bearing_error_deg": 1.14,
        "max_abs_bearing_error_deg": 2.56,
    },
}

# The per-sample budgets carry the 1023-tap doppler bandpass deliberately:
# realizing the filter took low_snr_dc's mean bearing error from 6.0 to 1.0
# degrees for 0.9-2.5 us/sample against the 20.8 us real-time budget.
for _limits in BASELINE_LIMITS.values():
    _limits["mean_us_per_sample"] = 2.60
    _limits["p95_us_per_sample"] = 3.60

# Each (method, scenario) is swept over this many buffer sizes; a regression
# dropping some must fail coverage even if the surviving rows are in-limit.
EXPECTED_BUFFER_SIZES = 4


def paths(out_dir: Path, profile: str) -> tuple[Path, Path, Path]:
    return (
        out_dir / "gate_bearing.jsonl",
        out_dir / f"bearing_performance_{profile}_summary.md",
        out_dir / f"bearing_performance_{profile}_failed_rows.jsonl",
    )


def run_example(metrics_path: Path) -> None:
    write_metrics(
        metrics_path,
        "bearing_performance",
        lambda handle: subprocess.run(
            ["cargo", "run", "--release", "-p", "rotaryclub-metrics", "--bin", "gate_bearing"],
            check=True,
            stdout=handle,
        ),
    )


def evaluate_thresholds(
    rows: list[dict[str, str]],
    profile: str,
    overrides: dict[str, float | None],
) -> tuple[list[str], list[dict[str, str]]]:
    profile_limits = {key: dict(val) for key, val in BASELINE_LIMITS.items()}
    failures: list[str] = []
    failed_rows: list[dict[str, str]] = []

    failures.extend(
        coverage_failures(rows, lambda row: (row["method"], row["scenario"]), BASELINE_LIMITS.keys())
    )
    failures.extend(
        fine_coverage_failures(
            rows,
            lambda row: (row["method"], row["scenario"]),
            lambda row: (row["buffer_size"],),
            lambda _group: EXPECTED_BUFFER_SIZES,
        )
    )

    for row in rows:
        key = (row["method"], row["scenario"])
        if key not in BASELINE_LIMITS:
            failures.append(f"FAIL unknown method/scenario row: {row}")
            failed_rows.append(
                {
                    **row,
                    **{f"limit_{m.name}": "" for m in METRICS},
                    "reason": "unknown method/scenario",
                }
            )
            continue

        limits = dict(profile_limits[key])
        for metric_name, value in overrides.items():
            if value is not None:
                limits[metric_name] = float(value)

        violations = evaluate_row_against_limits(row, limits, METRICS, EPSILON)
        unsupported = unsupported_metrics(
            row,
            limits,
            METRICS,
            exempt=SUPPORT_EXEMPT,
            physical_max=PHYSICAL_MAX,
        )
        if unsupported and not violations:
            # Passing by less than the row's own noise is not passing. Either
            # the draw count is too low for this margin or the value has
            # drifted close enough to its limit that the verdict is a coin
            # toss; both want attention before the gate starts flapping.
            failures.append(
                f"FAIL row: {row} (within limits but not supported by the "
                f"measurement: {','.join(unsupported)}; raise the draw count "
                f"or widen the margin)"
            )
            failed_rows.append({**row, "reason": "unsupported by the measurement"})
        if violations:
            observed = " ".join(f"{m.name}={m.format_value(float(row[m.name]))}" for m in METRICS)
            limits_text = " ".join(f"limit_{m.name}={m.format_value(limits[m.name])}" for m in METRICS)
            failures.append(
                f"FAIL row: {row} ({observed}; {limits_text}; violations={','.join(violations)})"
            )
            failed_rows.append(
                {
                    **row,
                    **{f"limit_{m.name}": m.format_value(limits[m.name]) for m in METRICS},
                    "reason": "threshold exceeded",
                }
            )

    return failures, failed_rows


def write_failed_rows(rows: list[dict[str, str]], failed_rows_path: Path, input_rows: list[dict[str, str]]) -> None:
    failed_rows_path.parent.mkdir(parents=True, exist_ok=True)
    input_fields = list(input_rows[0].keys()) if input_rows else []
    limit_fields = [f"limit_{m.name}" for m in METRICS]
    fieldnames = input_fields + limit_fields + ["reason"]
    with failed_rows_path.open("w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(json.dumps(row) + "\n")


def build_summary_lines(rows: list[dict[str, str]], profile: str) -> list[str]:
    grouped = summarize_rows(rows, group_keys=["method", "scenario"], metrics=METRICS)
    profile_limits = {key: dict(val) for key, val in BASELINE_LIMITS.items()}

    lines = [
        "# Bearing Performance Summary",
        "",
        f"- Profile: `{profile}`",
        "- Scope: bearing calculators only (correlation and zero-crossing), not end-to-end north+bearing pipeline.",
        "- This markdown file is the detailed metrics artifact generated from the JSONL metrics.",
        "- CI step-summary status notes are separate and only indicate pass/fail state.",
        "",
        "## Threshold Profile",
        "",
    ]
    lines.extend(["Using baseline thresholds.", ""])

    threshold_headers = ["method", "scenario", "threshold set"] + [f"limit {m.display_name}" for m in METRICS]
    threshold_aligns = ["left", "left", "left"] + ["right"] * len(METRICS)
    threshold_rows = []
    for method, scenario in sorted(BASELINE_LIMITS.keys()):
        lim = profile_limits[(method, scenario)]
        threshold_rows.append([method, scenario, f"{scenario}_{profile}"] + [m.format_value(lim[m.name]) for m in METRICS])
    lines.extend(render_markdown_table(threshold_headers, threshold_aligns, threshold_rows))

    lines.extend(["", "## Metrics", ""])
    metric_headers = ["method", "scenario", "rows"] + [m.display_name for m in METRICS]
    metric_aligns = ["left", "left", "right"] + ["right"] * len(METRICS)
    metric_rows = []
    for method, scenario in sorted(grouped.keys()):
        s = grouped[(method, scenario)]
        metric_rows.append([method, scenario, str(int(s["rows"]))] + [m.format_value(s[m.name]) for m in METRICS])
    lines.extend(render_markdown_table(metric_headers, metric_aligns, metric_rows))
    return lines


def append_failed_rows_md(lines: list[str], failed_rows_path: Path, max_rows: int) -> list[str]:
    lines.extend(["", "## Threshold Check", ""])
    if not failed_rows_path.exists():
        lines.append(f"`{failed_rows_path}` not found.")
        return lines
    _, rows = read_metrics(failed_rows_path)
    if not rows:
        lines.append("No threshold failures.")
        return lines
    lines.append(f"Threshold failures: {len(rows)} row(s)")
    lines.append("")
    headers = (
        ["method", "scenario", "buffer"]
        + [m.display_name for m in METRICS]
        + [f"limit {m.display_name}" for m in METRICS]
        + ["reason"]
    )
    aligns = ["left", "left", "right"] + ["right"] * (len(METRICS) * 2) + ["left"]
    table_rows = []
    for row in rows[:max_rows]:
        table_rows.append(
            [
                row.get("method", ""),
                row.get("scenario", ""),
                row.get("buffer_size", ""),
                *[row.get(m.name, "") for m in METRICS],
                *[row.get(f"limit_{m.name}", "") for m in METRICS],
                row.get("reason", ""),
            ]
        )
    lines.extend(render_markdown_table(headers, aligns, table_rows))
    if len(rows) > max_rows:
        lines.extend(["", f"Showing first {max_rows} rows."])
    return lines


def write_summary(metrics_path: Path, summary_path: Path, profile: str, failed_rows_path: Path | None, max_rows: int) -> None:
    meta, rows = read_metrics(metrics_path)
    assert_metrics_are_current(metrics_path, meta)
    lines = build_summary_lines(rows, profile)
    if failed_rows_path is not None:
        lines = append_failed_rows_md(lines, failed_rows_path, max_rows)
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def print_failed_rows_md(failed_rows_path: Path, title: str, max_rows: int) -> None:
    lines = [f"## {title}", ""]
    append_failed_rows_md(lines, failed_rows_path, max_rows)
    print("\n".join(lines))


def cmd_run(args: argparse.Namespace) -> int:
    metrics_path, _, _ = paths(args.out_dir, "baseline")
    print("Running bearing performance metrics example...")
    run_example(metrics_path)
    print(f"Wrote {metrics_path}")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    metrics_path, _, failed_rows_path = paths(args.out_dir, "baseline")
    meta, rows = read_metrics(metrics_path)
    assert_metrics_are_current(metrics_path, meta)
    overrides = {
        "success_rate": args.override_min_success_rate,
        "mean_us_per_sample": args.override_max_mean_us_per_sample,
        "p95_us_per_sample": args.override_max_p95_us_per_sample,
        "mean_abs_bearing_error_deg": args.override_max_mean_error_deg,
        "p95_abs_bearing_error_deg": args.override_max_p95_error_deg,
        "max_abs_bearing_error_deg": args.override_max_error_deg,
    }
    failures, failed_rows = evaluate_thresholds(rows, "baseline", overrides)
    write_failed_rows(failed_rows, failed_rows_path, rows)
    print(f"Wrote {failed_rows_path}")
    if failures:
        for failure in failures:
            print(failure)
        return 1
    print("Bearing performance thresholds (baseline): PASS")
    return 0


def cmd_summary(args: argparse.Namespace) -> int:
    metrics_path, summary_path, failed_rows_path = paths(args.out_dir, "baseline")
    include_failed = failed_rows_path if args.include_failed_rows else None
    write_summary(metrics_path, summary_path, "baseline", include_failed, args.max_rows)
    print(f"Wrote {summary_path}")
    return 0


def cmd_failed_rows(args: argparse.Namespace) -> int:
    print_failed_rows_md(args.failed_rows_path_arg, args.title, args.max_rows)
    return 0


def cmd_ci(args: argparse.Namespace) -> int:
    metrics_path, summary_path, failed_rows_path = paths(args.out_dir, "baseline")
    print("Running bearing performance metrics example...")
    run_example(metrics_path)
    print(f"Wrote {metrics_path}")

    meta, rows = read_metrics(metrics_path)
    assert_metrics_are_current(metrics_path, meta)
    overrides = {
        "success_rate": args.override_min_success_rate,
        "mean_us_per_sample": args.override_max_mean_us_per_sample,
        "p95_us_per_sample": args.override_max_p95_us_per_sample,
        "mean_abs_bearing_error_deg": args.override_max_mean_error_deg,
        "p95_abs_bearing_error_deg": args.override_max_p95_error_deg,
        "max_abs_bearing_error_deg": args.override_max_error_deg,
    }
    failures, failed_rows = evaluate_thresholds(rows, "baseline", overrides)
    write_failed_rows(failed_rows, failed_rows_path, rows)
    print(f"Wrote {failed_rows_path}")

    write_summary(metrics_path, summary_path, "baseline", failed_rows_path, args.max_rows)
    print(f"Wrote {summary_path}")

    if failures:
        for failure in failures:
            print(failure)
        return 1
    print("Bearing performance thresholds (baseline): PASS")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Bearing performance report tool")
    sub = parser.add_subparsers(dest="command", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--out-dir", type=Path, default=Path("target/bearing-perf"))

    for name in ("run", "check", "summary", "ci"):
        p = sub.add_parser(name, parents=[common])
        if name in {"check", "ci"}:
            p.add_argument("--override-min-success-rate", type=float, default=None)
            p.add_argument("--override-max-mean-us-per-sample", type=float, default=None)
            p.add_argument("--override-max-p95-us-per-sample", type=float, default=None)
            p.add_argument("--override-max-mean-error-deg", type=float, default=None)
            p.add_argument("--override-max-p95-error-deg", type=float, default=None)
            p.add_argument("--override-max-error-deg", type=float, default=None)
        if name in {"summary", "ci"}:
            p.add_argument("--max-rows", type=int, default=10)
        if name == "summary":
            p.add_argument("--include-failed-rows", action="store_true")

    pf = sub.add_parser("failed-rows")
    pf.add_argument("failed_rows_path_arg", type=Path)
    pf.add_argument("--title", default="Bearing Performance Threshold Failures (Top Rows)")
    pf.add_argument("--max-rows", type=int, default=10)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    if args.command == "run":
        return cmd_run(args)
    if args.command == "check":
        return cmd_check(args)
    if args.command == "summary":
        return cmd_summary(args)
    if args.command == "failed-rows":
        return cmd_failed_rows(args)
    if args.command == "ci":
        return cmd_ci(args)
    raise ValueError(f"unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
